# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '00 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 14
        days-before-close: 7
        
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        
        stale-issue-message: |
          This issue has been open for 14 days without any activity 😔
          
          If you're still working on this, please remove the `stale` label or add a comment to let us know 🙏🏻✅
          
          Otherwise, we'll consider this issue stale and will close it in 7 days ❌       
          
        stale-pr-message: |
          This pull request has been open for 14 days without any activity 😔
          
          If you're still working on this, please remove the `stale` label or add a comment to let us know 🙏🏻✅
          
          Otherwise, we'll consider this pull request stale and will close it in 7 days ❌
